warehouse:
  type: sqlite
  database: data/warehouse.sqlite

paths:
  raw: s3a://de-pipeline-test-853409708/raw
  bronze: s3a://de-pipeline-test-853409708/bronze
  silver: s3a://de-pipeline-test-853409708/silver
  reference: /app/data/reference #local

pipeline:
  days_back: 7

quality_rules:
  orders:
    - name: non_null_order_id
      column: order_id
      check: not_null
    - name: positive_amount
      column: amount
      check: gt_zero
  users:
    - name: unique_user_id
      column: user_id
      check: unique

# Cấu hình thêm cho cloud
gcp_project: ${GCP_PROJECT}
bq_dataset: ${BQ_DATASET}
bq_location: ${BQ_LOCATION}

# AWS S3 config
s3:
  bucket: de-pipeline-test-853409708
  raw_prefix: processed/


spark_conf:
  spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  spark.hadoop.fs.s3a.endpoint: s3.ap-southeast-1.amazonaws.com
  spark.hadoop.fs.s3a.region: ap-southeast-1
  spark.hadoop.fs.s3a.path.style.access: "true"   # an toàn, cứ bật

  # Timeout/retry giữ nguyên
  spark.hadoop.fs.s3a.connection.timeout: "60000"
  spark.hadoop.fs.s3a.connection.request.timeout: "5000"
  spark.hadoop.fs.s3a.connection.establish.timeout: "5000"
  spark.hadoop.fs.s3a.socket.timeout: "60000"
  spark.hadoop.fs.s3a.attempts.maximum: "3"
  spark.hadoop.fs.s3a.retry.limit: "3"
