- name: Restart Airflow & sync files
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    script: |
      set -e
      cd /home/${{ secrets.SERVER_USER }}

      echo "🧹 Sync DAGs and configs..."
      mkdir -p airflow/dags airflow/dags/pipelines airflow/configs
      cp -r airflow-deploy/airflow/dags/* airflow/dags/ || true
      cp -r airflow-deploy/pipelines/* airflow/dags/pipelines/ || true
      cp -r airflow-deploy/configs/* airflow/configs/ || true

      echo "🛠 Generate .env from GitHub Secrets..."
      cd /home/${{ secrets.SERVER_USER }}/airflow-deploy
      cat > .env <<EOL
      AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION=${{ secrets.AWS_REGION }}
      S3_BUCKET=${{ secrets.S3_BUCKET }}
      SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
      AIRFLOW__SMTP__SMTP_HOST=${{ secrets.AIRFLOW__SMTP__SMTP_HOST }}
      AIRFLOW__SMTP__SMTP_STARTTLS=${{ secrets.AIRFLOW__SMTP__SMTP_STARTTLS }}
      AIRFLOW__SMTP__SMTP_SSL=${{ secrets.AIRFLOW__SMTP__SMTP_SSL }}
      AIRFLOW__SMTP__SMTP_USER=${{ secrets.AIRFLOW__SMTP__SMTP_USER }}
      AIRFLOW__SMTP__SMTP_PASSWORD=${{ secrets.AIRFLOW__SMTP__SMTP_PASSWORD }}
      AIRFLOW__SMTP__SMTP_PORT=${{ secrets.AIRFLOW__SMTP__SMTP_PORT }}
      AIRFLOW__SMTP__SMTP_MAIL_FROM=${{ secrets.AIRFLOW__SMTP__SMTP_MAIL_FROM }}
      EOL

      echo "🔄 Restarting Airflow..."
      docker-compose restart airflow-webserver airflow-scheduler

      echo "✅ Deployment finished!"