name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - "airflow/dags/**"
      - "pipelines/**"
      - "configs/**"
      - "docker/**"
      - "docker-compose.yml"
      - ".env.example"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 🧾 Clone source code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 🐍 Setup Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # ✅ Install lint/test dependencies
      - name: Install dependencies
        run: |
          pip install flake8 pytest

      # 🧹 Run flake8 lint (không fail nếu lỗi style)
      - name: Run flake8 lint
        run: |
          flake8 airflow/dags/ pipelines/ configs/
        continue-on-error: true

      # ✅ Run pytest (basic tests)
      - name: Run unit tests
        run: |
          pytest -q --disable-warnings
        continue-on-error: true

      # 🔍 Debug file paths
      - name: Debug files in repo
        run: |
          echo "=== airflow/dags ==="
          ls -R airflow/dags || true
          echo "=== pipelines ==="
          ls -R pipelines || true
          echo "=== configs ==="
          ls -R configs || true

      # 🚀 Copy files to EC2 (via SCP)
      - name: Upload DAGs and configs to EC2 server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "airflow/dags/*,pipelines/*,configs/*,docker-compose.yml"
          target: /home/${{ secrets.SERVER_USER }}/airflow-deploy/

      # 🔄 Restart Airflow bằng lệnh cp thủ công
      - name: Restart Airflow & sync files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SERVER_USER }}

            echo "🧹 Sync DAGs and configs..."
            mkdir -p airflow/dags airflow/dags/pipelines airflow/configs
            cp -r airflow-deploy/airflow/dags/* airflow/dags/ || true
            cp -r airflow-deploy/pipelines/* airflow/dags/pipelines/ || true
            cp -r airflow-deploy/configs/* airflow/configs/ || true

            echo "🔄 Restarting Airflow..."
            cd /home/${{ secrets.SERVER_USER }}/airflow-deploy
            docker-compose restart airflow-webserver airflow-scheduler

            echo "✅ Deployment finished!"
