name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"
      - "pipelines/**"
      - "configs/**"
      - "docker/**"
      - "docker-compose.yml"
      - ".env.example"
  workflow_dispatch:   # Cho phép chạy thủ công từ UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          pip install flake8 pytest

      - name: Lint Python files
        run: |
          flake8 dags/ pipelines/ configs/ || true

      - name: Run pytest (basic tests)
        run: |
          pytest -q --disable-warnings || true

      # Copy DAGs & configs lên server qua SSH
      - name: Copy DAGs and configs to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: |
            dags/*.py
            pipelines/*.py
            configs/*.yaml
          target: /home/${{ secrets.SERVER_USER }}/airflow-deploy/

      # Restart Airflow trên server
      - name: Restart Airflow services
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/airflow-deploy/
            docker compose cp dags/. airflow-webserver:/opt/airflow/dags/
            docker compose cp pipelines/. airflow-webserver:/opt/airflow/dags/pipelines/
            docker compose cp configs/. airflow-webserver:/opt/airflow/configs/
            docker compose restart airflow-webserver airflow-scheduler